---
title: "Untitled"
author: "Lizzy Wilk"
date: "2/7/2023"
output: html_document
---

# required packages
```{r load packages}
library(recount)
library(recount3)
library(readr)
#source("./functions/rec3_rse_download.R") # change to where you have this function script saved
#source("./scripts/functions/lw_rec3_rse_download.R") 
```

# utilize function in rec3_rse_download.R
## NOTE: prerequisite is cellosaurus problematic cell line list that is available in this directory's /data folder, adjust cellosaurusfilepath and savefilepath accordingly 
```{r function run, message=FALSE, warning=FALSE}
#for(i in c("ccle", "hpa_c", "hpa_t", "pdx", "bone_t", "bone_n", "bone_c")){
# rec3_rse_download(project = i, cellosaurusfilepath = "../data/problematic_celllines.csv", savefilepath = "../data/recount3/") # will place full rse (with calc TPM), rawcounts, and tpm objects in destination folder
#}
```


```{r}
#gtex_rse(savefilepath = "../data/recount3/") #all tissues
gtex_rse(savefilepath = "../data/recount3/test/") #just 3 tissues

#assay(gtex_rse, "counts") <- transform_counts(gtex_rse)
#assays(gtex_rse)$TPM <- recount::getTPM(gtex_rse, length_var = "bp_length")
   
#gtex_rse <- readRDS("~/Documents/code_review/modelselection/data/recount3/test/rse/gtex_rse.rds") #just 3 tissues
gtex_rse <- readRDS("~/Documents/code_review/modelselection/data/recount3/rse/gtex_rse.rds") #all gtex tissues

 #gtex_rse(savefilepath = "../data/recount3/")
# should have assigned an rse object at this point, now need to generate tpm
  assay(gtex_rse, "counts") <- transform_counts(gtex_rse)
  assays(gtex_rse)$TPM <- recount::getTPM(gtex_rse, length_var = "bp_length")
  
  colSums(assay(gtex_rse, "TPM")) / 1e6 ## Should all be equal to 1
  
  #t <- assay(gtex_rse, "counts")
  
  # now, save RSE as object
#  saveRDS(rse, paste(savefilepath, "rse/", project, "_rse.rds", sep = ""))
  
  # also save raw counts and TPM individually
#  saveRDS(rse@assays@data@listData[["raw_counts"]], paste(savefilepath, "raw_counts/", project, "_rawcounts.rds", sep = ""))
#  saveRDS(rse@assays@data@listData[["TPM"]], paste(savefilepath, "tpm/", project, "_tpm.rds", sep = "")) 
```

```{r}
assays(gtex_rse)$counts <- transform_counts(gtex_rse)

assays(gtex_rse)$TPM <- recount::getTPM(gtex_rse)
```

```{r}
assays(rse_gene_SRP009615)$counts <- transform_counts(rse_gene_SRP009615)

assays(rse_gene_SRP009615)$TPM <- recount::getTPM(rse_gene_SRP009615)
```


### dissected function
```{r}
test <- function(project = "gtex", savefilepath){
  proj_home <- "data_sources/gtex"
  proj <- c("BRAIN", "SKIN", "ESOPHAGUS", "BLOOD", "BLOOD_VESSEL", "ADIPOSE_TISSUE", "HEART", "MUSCLE", "COLON", "THYROID", "NERVE", "LUNG", "BREAST", "TESTIS", "STOMACH", "PANCREAS", "PITUITARY", "ADRENAL_GLAND", "PROSTATE", "SPLEEN", "LIVER", "BONE_MARROW", "OVARY", "SMALL_INTESTINE", "SALIVARY_GLAND", "VAGINA", "UTERUS", "KIDNEY", "BLADDER", "CERVIX_UTERI", "FALLOPIAN_TUBE")
  #proj <- c("BLADDER", "CERVIX_UTERI", "FALLOPIAN_TUBE")
 
 # if (length(proj) > 1){
    # make list of all rse's, then collapse together
    temp_rse_list <- list()
    rse <- NULL
    for (i in proj){
      #temp_rse_list[[paste(i)]] <- recount3::create_rse_manual(
      t <- recount3::create_rse_manual(
        project = paste(i),
        project_home = proj_home,
        organism = "human",
        annotation = "gencode_v26",
        type = "gene"
        
      )
      assay(t, "counts") <- transform_counts(t)
      assays(t)$TPM <- recount::getTPM(t, length_var = "bp_length")
      #print(str(t))
      temp_rse_list[[paste(i)]] <- t
      #print(str(temp_rse_list))
      
 #     if (project == "tcga"){
  #      temp_rse_list[[paste(i)]] <- temp_rse_list[[paste(i)]][,grep("Primary", temp_rse_list[[paste(i)]]@colData@listData[["tcga.cgc_sample_sample_type"]])]
   #   }
      
   #   print(str(temp_rse_list))
    }
    #rse <- cbind(rse, temp_rse_list[[paste(i)]])
#    rse <- purrr::reduce(temp_rse_list, cbind) 
#    for(i in proj[-1]){
#      rse <- cbind(rse, temp_rse_list[[paste(i)]])  
#      print(str(rse))
#    }
    return(temp_rse_list)
  }
    # now, save RSE as object
#    saveRDS(rse, paste(savefilepath, "rse/", project, "_rse.rds", sep = ""))
#    saveRDS(rse@assays@data@listData[["raw_counts"]], paste(savefilepath, "raw_counts/", project, "_rawcounts.rds", sep = ""))
    
    # should have assigned an rse object at this point, now need to generate tpm
    #assay(rse, "counts") <- transform_counts(rse)
    #assays(rse)$TPM <- recount::getTPM(rse, length_var = "bp_length")
    

    # also save raw counts and TPM individually
#    saveRDS(rse@assays@data@listData[["TPM"]], paste(savefilepath, "tpm/", project, "_tpm.rds", sep = ""))
#}

t <- test(savefilepath = "../data/recount3/test/")
#t2 <- purrr::map(t, ~cbind())
t2 <- purrr::reduce(t, cbind)
```

### test new function
```{r}
#getgtex(savefilepath = "../data/recount3/test/")
getgtex(savefilepath = "../data/recount3/")
saveRDS(t, "../data/recount3/test/gtex_list_rse.rds")
```

### parallelize 
```{r}
library(foreach)
library(doParallel)
cl <- makeCluster(4)
registerDoParallel(cl, cores = 4)

test <- function(project = "gtex", savefilepath){
proj_home <- "data_sources/gtex"
  proj <- c("BRAIN", "SKIN", "ESOPHAGUS", "BLOOD", "BLOOD_VESSEL", "ADIPOSE_TISSUE", "HEART", "MUSCLE", "COLON", "THYROID", "NERVE", "LUNG", "BREAST", "TESTIS", "STOMACH", "PANCREAS", "PITUITARY", "ADRENAL_GLAND", "PROSTATE", "SPLEEN", "LIVER", "BONE_MARROW", "OVARY", "SMALL_INTESTINE", "SALIVARY_GLAND", "VAGINA", "UTERUS", "KIDNEY", "BLADDER", "CERVIX_UTERI", "FALLOPIAN_TUBE")
  #proj <- c("BLADDER", "CERVIX_UTERI", "FALLOPIAN_TUBE")
 
 # if (length(proj) > 1){
    # make list of all rse's, then collapse together
 #   temp_rse_list <- list()
#    rse <- NULL
foreach(i = 1:length(proj), .combine=cbind) %dopar% {
    #temp_rse_list[[paste(i)]] <- recount3::create_rse_manual(
    t <- recount3::create_rse_manual(
      project = proj[i],
      project_home = proj_home,
      organism = "human",
      annotation = "gencode_v26",
      type = "gene"
      
    )
    require(recount3)
    assay(t, "counts") <- recount3::transform_counts(t)
    assays(t)$TPM <- recount::getTPM(t, length_var = "bp_length")
    #print(str(t))
    #temp_rse_list[[paste(i)]] <- t
    #print(str(temp_rse_list))
    
    #     if (project == "tcga"){
    #      temp_rse_list[[paste(i)]] <- temp_rse_list[[paste(i)]][,grep("Primary", temp_rse_list[[paste(i)]]@colData@listData[["tcga.cgc_sample_sample_type"]])]
    #   }
    
    #   print(str(temp_rse_list))
   # now, save RSE as object
    saveRDS(rse, paste(savefilepath, "rse/", project, "_rse.rds", sep = ""))
    saveRDS(rse@assays@data@listData[["raw_counts"]], paste(savefilepath, "raw_counts/", project, "_rawcounts.rds", sep = ""))
    
    # should have assigned an rse object at this point, now need to generate tpm
    #assay(rse, "counts") <- transform_counts(rse)
    #assays(rse)$TPM <- recount::getTPM(rse, length_var = "bp_length")
    

    # also save raw counts and TPM individually
    saveRDS(rse@assays@data@listData[["TPM"]], paste(savefilepath, "tpm/", project, "_tpm.rds", sep = ""))
}
return(t)
}

t <- test(savefilepath = "../data/recount3/")
```


