---
title: "TumPurity"
output: html_document
date: '2022-09-06'
---

> generating tumor purity info based on TCGA to determine if tumor purity highly influences model performance

# purity information from: https://gdc.cancer.gov/about-data/publications/pancanatlas ABSOLUTE purity/ploidy file (220906)
# code for computation sourced then adjusted from: https://github.com/katharineyu/TCGA_CCLE_paper/blob/master/R_scripts/tumor_cell_line_cor.R

# load in data from pancanatlas
```{r load}
purity_info_pca <- read.csv("/Users/avery/Desktop/work/R Projects/modelselection/data/TCGA_mastercalls.abs_tables_JSedit.fixed.csv")

tcga_barcode <- strtrim(tcga_rse@colData@listData[["tcga.tcga_barcode"]],15)
  
# test <- setdiff(tcga_barcode, purity_info_pca$array) # 9759 represented, 336 not
```

# find highly tumor purity-associated genes
```{r computation}
TCGA <- assays(tcga_rse)$TPM
colnames(TCGA) <- tcga_barcode

TCGA <- TCGA[, intersect(purity_info_pca$array, colnames(TCGA))] 
tumors_purity <-  purity_info_pca[purity_info_pca$array %in% colnames(TCGA), ]
tmp <- lapply(rownames(TCGA), function(x)cor.test(as.numeric(TCGA[x,]),tumors_purity$purity, method = "s")) # returned lots of warnings 'Warning in cor.test.default(as.numeric(TCGA[x, ]), tumors_purity$purity,  :
  # Cannot compute exact p-value with ties'

tmp.df <- data.frame(sapply(tmp,function(x)x$p.value), sapply(tmp,function(x)x$estimate))
rownames(tmp.df) <- rownames(TCGA)
colnames(tmp.df) <- c("pvalue", "rho")
tmp.df$padj <- p.adjust(tmp.df$pvalue)
tmp.df.sig <- tmp.df[tmp.df$padj < 0.01 & tmp.df$rho < -0.4 & complete.cases(tmp.df),]
purity_genes <- rownames(tmp.df.sig)
TCGA <- TCGA[!(rownames(TCGA) %in% purity_genes),]
```

# save tumor purity-associated genes
```{r save}
saveRDS(purity_genes, "/Users/avery/Desktop/work/R Projects/modelselection/data/purity_genes.rds")
```

# clean env
```{r clean env}
rm(purity_info_pca, tcga_barcode, TCGA, tumors_purity, tmp, tmp.df, tmp.df.sig, purity_genes)
```